FROM mcr.microsoft.com/devcontainers/python
RUN sudo apt-get install python3 python3-venv python3-pip
# use this Dockerfile to install additional tools you might need, e.g.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
